name = "amour-gemini-proxy"
main = "cf-worker/src/index.ts"
compatibility_date = "2024-09-01"

# Example of routes (replace with your domain/zone)
# routes = [
#   { pattern = "example.com/api/gemini/*", zone_name = "example.com" }
# ]

[vars]
# No plaintext key here. Use `wrangler secret put GEMINI_API_KEY`.